INSERT INTO artist VALUES (1, "Dawn of Midi");
INSERT INTO artist VALUES (2, "Interpol");
INSERT INTO artist VALUES (3, "The Chrome Cranks");
INSERT INTO artist VALUES (4, "Melvins");
INSERT INTO artist VALUES (5, "Mogwai");
INSERT INTO artist VALUES (6, "Warpaint");

INSERT INTO album VALUES (1, 1, "Dysnomia");
INSERT INTO album VALUES (2, 1, "Turn on the Bright Lights");
INSERT INTO album VALUES (3, 1, "Dead Cool");
INSERT INTO album VALUES (4, 1, "Houdini");
INSERT INTO album VALUES (5, 1, "Come on Die Young");
INSERT INTO album VALUES (5, 2, "Every Country’s Sun");
INSERT INTO album VALUES (6, 1, "Heads Up");

INSERT INTO track VALUES (1, 1, 1, 'Io', '6.03');
INSERT INTO track VALUES (1, 1, 2, 'Sinope', '6.53');
INSERT INTO track VALUES (1, 1, 3, 'Atlas', '6.37');
INSERT INTO track VALUES (1, 1, 4, 'Nix', '3.39');
INSERT INTO track VALUES (1, 1, 5, 'Moon', '5.04');
INSERT INTO track VALUES (1, 1, 6, 'Ymir', '4.27');
INSERT INTO track VALUES (1, 1, 7, 'Ijiraq', '5.22');
INSERT INTO track VALUES (1, 1, 8, 'Algol', '4.16');
INSERT INTO track VALUES (1, 1, 9, 'Dysnomia', '4.14');

INSERT INTO track VALUES (2, 1, 1, 'Untitled', '3.57');
INSERT INTO track VALUES (2, 1, 2, 'Obstacle 1', '4.11');
INSERT INTO track VALUES (2, 1, 3, 'NYC', '4.20');
INSERT INTO track VALUES (2, 1, 4, 'PDA', '5.00');
INSERT INTO track VALUES (2, 1, 5, 'Say Hello to the Angels', '4.28');
INSERT INTO track VALUES (2, 1, 6, 'Hands Away', '3.06');
INSERT INTO track VALUES (2, 1, 7, 'Obstacle 2', '3.47');
INSERT INTO track VALUES (2, 1, 8, 'Stella Was a Diver and She Was Always Down', '6.28');
INSERT INTO track VALUES (2, 1, 9, 'Roland', '3.36');
INSERT INTO track VALUES (2, 1, 10, 'The New', '6.07');
INSERT INTO track VALUES (2, 1, 11, 'Leif Erikson', '4.00');

INSERT INTO track VALUES (3, 1, 1, 'Dead Cool', '5.25');
INSERT INTO track VALUES (3, 1, 2, 'Desperate Friend', '2.04');
INSERT INTO track VALUES (3, 1, 3, 'Way-Out Lover', '3.08');
INSERT INTO track VALUES (3, 1, 4, 'Down So Low', '3.55');
INSERT INTO track VALUES (3, 1, 5, 'Bloodshot Eye', '3.54');
INSERT INTO track VALUES (3, 1, 6, 'Nightmare in Pink', '2.06');
INSERT INTO track VALUES (3, 1, 7, 'Shine It On', '4.15');
INSERT INTO track VALUES (3, 1, 8, 'Burn Baby Burn', '6.13');

INSERT INTO track VALUES (4, 1, 1, 'Hooch', '2.49');
INSERT INTO track VALUES (4, 1, 2, 'Night Goat', '4.41');
INSERT INTO track VALUES (4, 1, 3, 'Lizzy', '4.44');
INSERT INTO track VALUES (4, 1, 4, 'Goin’ Blind', '4.33');
INSERT INTO track VALUES (4, 1, 5, 'Honey Bucket', '3.01');
INSERT INTO track VALUES (4, 1, 6, 'Hag Me', '7.06');
INSERT INTO track VALUES (4, 1, 7, 'Set Me Straight', '2.25');
INSERT INTO track VALUES (4, 1, 8, 'Sky Pup', '3.50');
INSERT INTO track VALUES (4, 1, 9, 'Joan of Arc', '3.36');
INSERT INTO track VALUES (4, 1, 10, 'Teet', '2.52');
INSERT INTO track VALUES (4, 1, 11, 'Copache', '2.07');
INSERT INTO track VALUES (4, 1, 12, 'Pearl Bomb', '2.46');
INSERT INTO track VALUES (4, 1, 13, 'Spread Eagle Beagle', '10.14');

INSERT INTO track VALUES (5, 1, 1, 'Punk Rock:', '2.09');
INSERT INTO track VALUES (5, 1, 2, 'Cody', '6.33');
INSERT INTO track VALUES (5, 1, 3, 'Helps Both Ways', '4.53');
INSERT INTO track VALUES (5, 1, 4, 'Year 2000 Non-Compliant Cardia', '3.26');
INSERT INTO track VALUES (5, 1, 5, 'Kappa', '4.53');
INSERT INTO track VALUES (5, 1, 6, 'Waltz for Aidan', '3.44');
INSERT INTO track VALUES (5, 1, 7, 'May Nothing But Happiness Come Through Your Door', '8.30');
INSERT INTO track VALUES (5, 1, 8, 'Oh! How the Dogs Stack Up', '2.04');
INSERT INTO track VALUES (5, 1, 9, 'Ex-Cowboy', '9.09');
INSERT INTO track VALUES (5, 1, 10, 'Chocky', '9.23');
INSERT INTO track VALUES (5, 1, 11, 'Christmas Steps', '10.39');
INSERT INTO track VALUES (5, 1, 12, 'Punk Rock/Puff Daddy/Antichrist', '2.14');

INSERT INTO track VALUES (5, 2, 1, 'Coolverine', '6.17');
INSERT INTO track VALUES (5, 2, 2, 'Party in the Dark', '4.02');
INSERT INTO track VALUES (5, 2, 3, 'Brain Sweeties', '4.44');
INSERT INTO track VALUES (5, 2, 4, 'Crossing the Road Material', '6.58');
INSERT INTO track VALUES (5, 2, 5, 'aka 47', '4.16');
INSERT INTO track VALUES (5, 2, 6, '20 Size', '4.44');
INSERT INTO track VALUES (5, 2, 7, '1000 Foot Face', '4.31');
INSERT INTO track VALUES (5, 2, 8, 'Don’t Believe the Fife', '6.24');
INSERT INTO track VALUES (5, 2, 9, 'Battered at a Scramble', '4.03');
INSERT INTO track VALUES (5, 2, 10, 'Old Poisons', '4.30');
INSERT INTO track VALUES (5, 2, 11, 'Every Country’s Sun', '5.38');

INSERT INTO track VALUES (6, 1, 1, 'Whiteout', '4.42');
INSERT INTO track VALUES (6, 1, 2, 'By Your Side', '4.32');
INSERT INTO track VALUES (6, 1, 3, 'New Song', '4.16');
INSERT INTO track VALUES (6, 1, 4, 'The Stall', '4.56');
INSERT INTO track VALUES (6, 1, 5, 'So Good', '5.59');
INSERT INTO track VALUES (6, 1, 6, 'Don’t Wanna', '3.43');
INSERT INTO track VALUES (6, 1, 7, 'Don’t Let Go', '4.22');
INSERT INTO track VALUES (6, 1, 8, 'Dre', '3.59');
INSERT INTO track VALUES (6, 1, 9, 'Heads Up', '4.57');
INSERT INTO track VALUES (6, 1, 10, 'Above Control', '5.06');
INSERT INTO track VALUES (6, 1, 11, 'Today Dear', '4.49');

INSERT INTO played VALUES (1, 1, 1, "20060814102103");
INSERT INTO played VALUES (2, 1, 1, "20060814102522");
INSERT INTO played VALUES (3, 1, 1, "20060814103025");
INSERT INTO played VALUES (4, 1, 1, "20060814103654");
INSERT INTO played VALUES (5, 1, 1, "20060814104143");
INSERT INTO played VALUES (5, 2, 1, "20060814104337");
INSERT INTO played VALUES (6, 1, 1, "20060814104721");

INSERT INTO contains VALUES ("Dysnomia", "Io");
INSERT INTO contains VALUES ("Dysnomia", "Sinope");
INSERT INTO contains VALUES ("Dysnomia", "Atlas");
INSERT INTO contains VALUES ("Dysnomia", "Nix");
INSERT INTO contains VALUES ("Dysnomia", "Moon");
INSERT INTO contains VALUES ("Dysnomia", "Ymir");
INSERT INTO contains VALUES ("Dysnomia", "Ijiraq");
INSERT INTO contains VALUES ("Dysnomia", "Algol");
INSERT INTO contains VALUES ("Dysnomia", "Dysnomia");

INSERT INTO contains VALUES ("Turn on the bright lights", "Untitled");
INSERT INTO contains VALUES ("Turn on the bright lights", "Obstacle 1");
INSERT INTO contains VALUES ("Turn on the bright lights", "NYC");
INSERT INTO contains VALUES ("Turn on the bright lights", "PDA");
INSERT INTO contains VALUES ("Turn on the bright lights", "Say Hello to the Angels");
INSERT INTO contains VALUES ("Turn on the bright lights", "Hands Away");
INSERT INTO contains VALUES ("Turn on the bright lights", "Obstacle 2");
INSERT INTO contains VALUES ("Turn on the bright lights", "Stella was a Diver and She Was Always Down");
INSERT INTO contains VALUES ("Turn on the bright lights", "Roland");
INSERT INTO contains VALUES ("Turn on the bright lights", "The New");
INSERT INTO contains VALUES ("Turn on the bright lights", "Leif Erikson");

INSERT INTO contains VALUES ("Dead Cool", "Dead Cool");
INSERT INTO contains VALUES ("Dead Cool", "Desperate Friend");
INSERT INTO contains VALUES ("Dead Cool", "Way-Out Lover");
INSERT INTO contains VALUES ("Dead Cool", "Down So Low");
INSERT INTO contains VALUES ("Dead Cool", "Bloodshot Eye");
INSERT INTO contains VALUES ("Dead Cool", "Nightmare in Pink");
INSERT INTO contains VALUES ("Dead Cool", "Shine It On");
INSERT INTO contains VALUES ("Dead Cool", "Burn Baby Burn");

INSERT INTO contains VALUES ("Houdini", "Hooch");
INSERT INTO contains VALUES ("Houdini", "Night Goat");
INSERT INTO contains VALUES ("Houdini", "Lizzy");
INSERT INTO contains VALUES ("Houdini", "Goin' Blind");
INSERT INTO contains VALUES ("Houdini", "Honey Bucket");
INSERT INTO contains VALUES ("Houdini", "Hag Me");
INSERT INTO contains VALUES ("Houdini", "Set Me Straight");
INSERT INTO contains VALUES ("Houdini", "Sky Pup");
INSERT INTO contains VALUES ("Houdini", "Joan of Arc");
INSERT INTO contains VALUES ("Houdini", "Teet");
INSERT INTO contains VALUES ("Houdini", "Copache");
INSERT INTO contains VALUES ("Houdini", "Pearl Bomb");
INSERT INTO contains VALUES ("Houdini", "Spread Eagle Beagle");

INSERT INTO contains VALUES ("Come on Die Young", "Punk Rock:");
INSERT INTO contains VALUES ("Come on Die Young", "Cody");
INSERT INTO contains VALUES ("Come on Die Young", "Helps Both Ways");
INSERT INTO contains VALUES ("Come on Die Young", "Year 2000 Non-Compliant Cardia");
INSERT INTO contains VALUES ("Come on Die Young", "Kappa");
INSERT INTO contains VALUES ("Come on Die Young", "Waltz of Aidan");
INSERT INTO contains VALUES ("Come on Die Young", "May Nothing But Happiness Come Through Your Door");
INSERT INTO contains VALUES ("Come on Die Young", "Oh! How the Dogs Stack up");
INSERT INTO contains VALUES ("Come on Die Young", "Ex-Cowboy");
INSERT INTO contains VALUES ("Come on Die Young", "Chocky");
INSERT INTO contains VALUES ("Come on Die Young", "Christmas Steps");
INSERT INTO contains VALUES ("Come on Die Young", "Punk Rock/Puff Daddy/Antichrist");

INSERT INTO contains VALUES ("Every Country's Sun", "Coolverine");
INSERT INTO contains VALUES ("Every Country's Sun", "Party in the Dark");
INSERT INTO contains VALUES ("Every Country's Sun", "Brain Sweeties");
INSERT INTO contains VALUES ("Every Country's Sun", "Crossing the Road Material");
INSERT INTO contains VALUES ("Every Country's Sun", "aka 47");
INSERT INTO contains VALUES ("Every Country's Sun", "20 Size");
INSERT INTO contains VALUES ("Every Country's Sun", "1000 Foot Face");
INSERT INTO contains VALUES ("Every Country's Sun", "Don't Believe the Fife");
INSERT INTO contains VALUES ("Every Country's Sun", "Battered at a Scramble");
INSERT INTO contains VALUES ("Every Country's Sun", "Old Poisons");
INSERT INTO contains VALUES ("Every Country's Sun", "Every Country's Sun");

INSERT INTO contains VALUES ("Heads Up", "Whiteout");
INSERT INTO contains VALUES ("Heads Up", "By Your Side");
INSERT INTO contains VALUES ("Heads Up", "New Song");
INSERT INTO contains VALUES ("Heads Up", "The Stall");
INSERT INTO contains VALUES ("Heads Up", "So Good");
INSERT INTO contains VALUES ("Heads Up", "Dont't Wanna");
INSERT INTO contains VALUES ("Heads Up", "Don't Let Go");
INSERT INTO contains VALUES ("Heads Up", "Dre");
INSERT INTO contains VALUES ("Heads Up", "Heads Up");
INSERT INTO contains VALUES ("Heads Up", "Above Control");
INSERT INTO contains VALUES ("Heads Up", "Today Dear");

INSERT INTO compiles VALUES ("Dawn of Midi", "Dysnomia");
INSERT INTO compiles VALUES ("Interpol", "Turn on the Bright Lights");
INSERT INTO compiles VALUES ("The Chrome Cranks", "Dead Cool");
INSERT INTO compiles VALUES ("Melvins", "Houdini");
INSERT INTO compiles VALUES ("Mogwai", "Come on Die Young");
INSERT INTO compiles VALUES ("Mogwai", "Every Country's Sun");
INSERT INTO compiles VALUES ("Warpaint", "Heads Up");
